# Visualizando dato y extrayendo metricas

In [ ]:
import pandas as pd
Financiamientos=pd.read_csv("Financiamientos_2026.csv") #hubo que cambiar año por anio
Financiamientos.head(5) # Imprimimos las primeras 5 filas del csv

,anio,mes,cve_ent,entidad,cve_mun,municipio,organismo,modalidad,destino,tipo,sexo,edad_rango,ingresos_rango,vivienda_valor,acciones,monto
0,2026,1,1,Aguascalientes,NaN,No distribuido,4,3,1,1,NaN,NaN,NaN,NaN,0.0,122400.0
1,2026,1,1,Aguascalientes,1.0,Aguascalientes,2,1,2,2,1.0,1.0,3.0,4.0,1.0,1122000.0
2,2026,1,1,Aguascalientes,1.0,Aguascalientes,2,1,2,2,1.0,2.0,4.0,4.0,1.0,1309428.0
3,2026,1,1,Aguascalientes,1.0,Aguascalientes,2,1,2,2,2.0,2.0,1.0,4.0,1.0,1002567.0
4,2026,1,1,Aguascalientes,1.0,Aguascalientes,2,1,2,2,2.0,2.0,4.0,5.0,1.0,1975821.0

In [43]:
# Obtenemos tamaños y tipos de dato
print(f"Tenemos {len(Financiamientos)} ejemplos")
print(f'Tenemos {len(Financiamientos.columns)} caracteristicas')
print("\n")
print(Financiamientos.info())

Tenemos 41971 ejemplos
Tenemos 16 caracteristicas


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41971 entries, 0 to 41970
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   anio            41971 non-null  int64
 1   mes             41971 non-null  int64
 2   cve_ent         41971 non-null  int64
 3   entidad         41971 non-null  object
 4   cve_mun         41945 non-null  float64
 5   municipio       41971 non-null  object
 6   organismo       41971 non-null  int64
 7   modalidad       41971 non-null  int64
 8   destino         41971 non-null  int64
 9   tipo            41971 non-null  int64
 10  sexo            41945 non-null  float64
 11  edad_rango      40988 non-null  float64
 12  ingresos_rango  41631 non-null  float64
 13  vivienda_valor  31555 non-null  float64
 14  acciones        41971 non-null  float64
 15  monto           41971 non-null  float64
dtypes: float64(7), int64(7), object(2)
memory usage: 5.1+ MB
None

In [44]:
#Obtenemos estadisticas basicas de cada columna
Financiamientos.describe()

,anio,mes,cve_ent,cve_mun,organismo,modalidad,destino,tipo,sexo,edad_rango,ingresos_rango,vivienda_valor,acciones,monto
count,41971.0,41971.000000,41971.000000,41945.000000,41971.000000,41971.000000,41971.000000,41971.000000,41945.000000,40988.000000,41631.000000,31555.000000,41971.000000,4.197100e+04
mean,2026.0,1.496676,16.582045,41.755108,1.437326,2.025875,2.369017,1.395440,1.423817,1.804528,3.511926,3.783362,2.596984,1.774852e+06
std,0.0,0.499995,8.295177,49.069213,1.261817,0.944037,1.420590,0.488951,0.494168,0.505849,1.583483,1.068413,6.362559,3.770674e+06
min,2026.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000e+00
25%,2026.0,1.000000,11.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,1.000000,0.000000e+00
50%,2026.0,1.000000,15.000000,28.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,3.000000,4.000000,1.000000,9.000000e+05
75%,2026.0,2.000000,23.000000,53.000000,2.000000,3.000000,3.000000,2.000000,2.000000,2.000000,5.000000,4.000000,2.000000,1.952087e+06
max,2026.0,2.000000,32.000000,570.000000,26.000000,4.000000,18.000000,2.000000,2.000000,3.000000,6.000000,6.000000,386.000000,1.375468e+08

## Leamos el diccionario de financiamiento para entender las variables

In [49]:
diccionario=pd.read_excel("diccionario_financiamiento.xlsx")
# mostramos los primeros valores
for i in range(len(diccionario)):
    if not(pd.isna(diccionario["Nemónico del campo"][i])):
        print(f'El campo {diccionario["Nemónico del campo"][i]} es: {diccionario["Alias"][i]}\nCon descripción: {diccionario["Descripción"][i]}\n')

El campo año es: Año
Con descripción: Año

El campo mes es: Mes
Con descripción: Mes

El campo cve_ent es: Clave de entidad federativa
Con descripción: Clave de la entidad federativa, de acuerdo con el catálogo de entidades federativas, municipios y localidades del Instituto Nacional de Estadística y Geografía (INEGI),  en la que se ejerció el financiamiento

El campo entidad es: Nombre de la entidad federativa
Con descripción: Nombre de la entidad federativa, de acuerdo con el catálogo de entidades federativas, municipios y localidades del INEGI, en la que se ejerció el financiamiento

El campo cve_mun es: Clave municipal
Con descripción: Clave del  municipio, de acuerdo con el catálogo de entidades federativas, municipios y localidades del Instituto Nacional de Estadística y Geografía (INEGI),  en la que se ejerció el financiamiento

El campo municipio es: Nombre del municipio
Con descripción: Nombre del municipio, de acuerdo con el catálogo de entidades federativas, municipios y localidades del INEGI, en la que se ejerció el financiamiento

El campo sexo es: Sexo
Con descripción: Sexo de los acreditado(a)s

El campo edad_rango es: Rango de edad
Con descripción: Rango de edad en años de los acreditados

El campo ingresos_rango es: Rangos de ingresos mensuales del acreditado
Con descripción: Rango de ingresos de los acreditados expresados en Unidades de Medida y Actualización (UMAs) mensuales

El campo vivienda_valor es: Valor de la vivienda clasificado en: Económica, Popular, Tradicional, Media, Residencial y Residencial plus.
Con descripción: Valor de la vivienda

Económica. Superficie construida en promedio: 40m2, costo promedio: 118 UMAs cuentan con 1 baño, cocina, área de usos múltiples.

Popular. Superficie construida en promedio: 50m2, costo promedio: de 118.1 a 200 UMAs cuentan con 1 baño, cocina, estancia, comedor, de 1 a 2 recámaras y 1 cajón de estacionamiento.

Tradicional. Superficie construida en promedio: 71m2, costo promedio: de 200.1 a 350 UMAs cuentan con 1 y ½ baños, cocina, estancia-comedor, de 2 a 3 recámaras, 1 cajón de estacionamiento.

Media. Superficie construida en promedio: 102m2, costo promedio: de 350.1 a 750 UMAs cuentan con 2 baños, cocina, sala, comedor, de 2 a 3 recámaras, cuarto de servicio y 1 a 2 cajones de estacionamiento.

Residencial. Superficie construida en promedio: 156m2, costo promedio: de 750.1 a 1,500 UMAs cuentan con 3 a 4 baños, cocina, sala, comedor, de 3 a 4 recámaras, cuarto de servicio, sala familiar y 2 o 3 cajones de estacionamiento.

Residencial plus. Superficie construida en promedio: más de 156m2, costo promedio: más de 750.1 a 1,500 UMAs cuentan con más de 4 años, cocina, sala, comedor, más de 4 recámaras, cuarto de servicio, sala familiar y más de 3 cajones de estacionamiento.

El campo organismo es: Organismo financiador
Con descripción: Organismo que financió la solución de vivienda

El campo tipo es: Tipo de financiamiento
Con descripción: Tipo de financiamiento

El campo modalidad es: Modalidad del financiamiento
Con descripción: Solución para la cual se dirige el ejercimiento del financiamiento

El campo destino es: Destino del financiamiento
Con descripción: Destinos de los financiamientos

El campo acciones es: Número de acciones
Con descripción: Número de acciones

El campo monto es: Monto de financiamiento
Con descripción: Monto de los financiamientos en pesos